version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - nextjs-network
    volumes:
      - .:/app
    command: ["npm", "run", "start"]

networks:
  nextjs-network:
    driver: bridge
